version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
      - env
      - npm i -g npm
      - npm install
  build:
    commands:
      - cat /proc/sys/fs/inotify/max_user_watches
      - npm run build
      - npm run test:cypress
      # TODO: Turn on cypress-tests again when problem with filewatchers solved
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: dlr-frontend
