version: 0.2

phases:
  install:
    commands:
      - env
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: dlr-frontend
