version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - env
      - npm i -g npm
      - npm install
  build:
    commands:
      - cat /proc/sys/fs/inotify/max_user_watches
      - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - cat /proc/sys/fs/inotify/max_user_watches
      - npm run build
      - npm run test:cypress
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: dlr-frontend
