version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - env
      - npm -v
      - node -v
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: dlr-frontend
